apiVersion: v1
kind: Service
metadata:
  name: airflow-svc
  namespace: mvdls3perf  
  labels:
    name: airflow-svc
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30007
  selector:
    app: airflow-web
