namespace: mvdls3perf

persistence:
  enabled: true
  existingClaim: mvdls3perf-pvc
  subPath: airflow

postgresql:
  enabled: true
  postgresqlDatabase: airflow
  auth:
    username: airflow
    password: airflow
  persistence:
    enabled: true
    existingClaim: mvdls3perf-pvc
    subPath: airflow/postgresql
    
redis:
  enabled: true

airflow:
  executor: "CeleryExecutor"
  extraVolumes:
    - name: airflow-pvc
      persistentVolumeClaim:
        claimName: mvdls3perf-pvc
  extraVolumeMounts: 
    - name: airflow-pvc
      mountPath: /opt/airflow/logs
      subPath: airflow/logs
  config:
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__CORE__LOGGING_LEVEL: "INFO"
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"

web:
  port: 8080
  replicas: 1
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 1

scheduler:
  replicas: 1
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 1

workers:
  replicas: 1
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 1

flower:
  enabled: true
  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: 500m

externalDatabase:
  type: postgresql
  host: postgresql.airflow
  port: 5432
  database: airflow
  user: airflow

fernetKey: ""
