apiVersion: v1
kind: Namespace
metadata:
  name: mvdls3perf

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mvdls3perf-pvc
  namespace: mvdls3perf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
